Unit 6
alder154/Javascript_tasks pull request #4
Opened 2022-03-17 17:11 UTC by alder154

2022-03-18 08:11 UTC, rimus requested changes

2022-03-18 08:11 UTC, rimus commented on 6. Prototypes.js
You also need to make classes inheritance here.

2022-03-18 16:24 UTC, alder154 commented on 6. Prototypes.js
No mention for classes inheritance there. But'll add
<img width="1070" alt="Снимок экрана 2022-03-18 в 19 20 35" src="https://user-images.githubusercontent.com/99394088/159042434-37546f1b-bff6-48d0-a357-994546eb15fb.png">

2022-03-23 10:30 UTC, rimus commented on 6. Prototypes.js
Hmm. Maybe tasks were changed. Ok, i understood. Thanks.

2022-03-23 10:31 UTC, rimus approved these changes
Looks good.

2022-03-23 10:47 UTC, merged